//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix_Supplier_Application.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCard", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        private int AvailableAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        private decimal PriceField;
        
        private System.Nullable<System.DateTime> LastUpdatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AvailableAmount {
            get {
                return this.AvailableAmountField;
            }
            set {
                if ((this.AvailableAmountField.Equals(value) != true)) {
                    this.AvailableAmountField = value;
                    this.RaisePropertyChanged("AvailableAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name searchTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProducts", ReplyAction="*")]
        TechFix_Supplier_Application.ProductService.SearchProductsResponse SearchProducts(TechFix_Supplier_Application.ProductService.SearchProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.SearchProductsResponse> SearchProductsAsync(TechFix_Supplier_Application.ProductService.SearchProductsRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProduct", ReplyAction="*")]
        TechFix_Supplier_Application.ProductService.InsertProductResponse InsertProduct(TechFix_Supplier_Application.ProductService.InsertProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.InsertProductResponse> InsertProductAsync(TechFix_Supplier_Application.ProductService.InsertProductRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllListedProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllListedProducts", ReplyAction="*")]
        TechFix_Supplier_Application.ProductService.GetAllListedProductsResponse GetAllListedProducts(TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllListedProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.GetAllListedProductsResponse> GetAllListedProductsAsync(TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchProducts", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.ProductService.SearchProductsRequestBody Body;
        
        public SearchProductsRequest() {
        }
        
        public SearchProductsRequest(TechFix_Supplier_Application.ProductService.SearchProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int supplierID;
        
        public SearchProductsRequestBody() {
        }
        
        public SearchProductsRequestBody(string searchTerm, int supplierID) {
            this.searchTerm = searchTerm;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.ProductService.SearchProductsResponseBody Body;
        
        public SearchProductsResponse() {
        }
        
        public SearchProductsResponse(TechFix_Supplier_Application.ProductService.SearchProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFix_Supplier_Application.ProductService.ProductCard[] SearchProductsResult;
        
        public SearchProductsResponseBody() {
        }
        
        public SearchProductsResponseBody(TechFix_Supplier_Application.ProductService.ProductCard[] SearchProductsResult) {
            this.SearchProductsResult = SearchProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProduct", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.ProductService.InsertProductRequestBody Body;
        
        public InsertProductRequest() {
        }
        
        public InsertProductRequest(TechFix_Supplier_Application.ProductService.InsertProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int supplierId;
        
        public InsertProductRequestBody() {
        }
        
        public InsertProductRequestBody(string title, string description, string filePath, int supplierId) {
            this.title = title;
            this.description = description;
            this.filePath = filePath;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.ProductService.InsertProductResponseBody Body;
        
        public InsertProductResponse() {
        }
        
        public InsertProductResponse(TechFix_Supplier_Application.ProductService.InsertProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertProductResult;
        
        public InsertProductResponseBody() {
        }
        
        public InsertProductResponseBody(int InsertProductResult) {
            this.InsertProductResult = InsertProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllListedProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllListedProducts", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.ProductService.GetAllListedProductsRequestBody Body;
        
        public GetAllListedProductsRequest() {
        }
        
        public GetAllListedProductsRequest(TechFix_Supplier_Application.ProductService.GetAllListedProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllListedProductsRequestBody {
        
        public GetAllListedProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllListedProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllListedProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.ProductService.GetAllListedProductsResponseBody Body;
        
        public GetAllListedProductsResponse() {
        }
        
        public GetAllListedProductsResponse(TechFix_Supplier_Application.ProductService.GetAllListedProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllListedProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFix_Supplier_Application.ProductService.ProductCard[] GetAllListedProductsResult;
        
        public GetAllListedProductsResponseBody() {
        }
        
        public GetAllListedProductsResponseBody(TechFix_Supplier_Application.ProductService.ProductCard[] GetAllListedProductsResult) {
            this.GetAllListedProductsResult = GetAllListedProductsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : TechFix_Supplier_Application.ProductService.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<TechFix_Supplier_Application.ProductService.ProductServiceSoap>, TechFix_Supplier_Application.ProductService.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Supplier_Application.ProductService.SearchProductsResponse TechFix_Supplier_Application.ProductService.ProductServiceSoap.SearchProducts(TechFix_Supplier_Application.ProductService.SearchProductsRequest request) {
            return base.Channel.SearchProducts(request);
        }
        
        public TechFix_Supplier_Application.ProductService.ProductCard[] SearchProducts(string searchTerm, int supplierID) {
            TechFix_Supplier_Application.ProductService.SearchProductsRequest inValue = new TechFix_Supplier_Application.ProductService.SearchProductsRequest();
            inValue.Body = new TechFix_Supplier_Application.ProductService.SearchProductsRequestBody();
            inValue.Body.searchTerm = searchTerm;
            inValue.Body.supplierID = supplierID;
            TechFix_Supplier_Application.ProductService.SearchProductsResponse retVal = ((TechFix_Supplier_Application.ProductService.ProductServiceSoap)(this)).SearchProducts(inValue);
            return retVal.Body.SearchProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.SearchProductsResponse> TechFix_Supplier_Application.ProductService.ProductServiceSoap.SearchProductsAsync(TechFix_Supplier_Application.ProductService.SearchProductsRequest request) {
            return base.Channel.SearchProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.SearchProductsResponse> SearchProductsAsync(string searchTerm, int supplierID) {
            TechFix_Supplier_Application.ProductService.SearchProductsRequest inValue = new TechFix_Supplier_Application.ProductService.SearchProductsRequest();
            inValue.Body = new TechFix_Supplier_Application.ProductService.SearchProductsRequestBody();
            inValue.Body.searchTerm = searchTerm;
            inValue.Body.supplierID = supplierID;
            return ((TechFix_Supplier_Application.ProductService.ProductServiceSoap)(this)).SearchProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Supplier_Application.ProductService.InsertProductResponse TechFix_Supplier_Application.ProductService.ProductServiceSoap.InsertProduct(TechFix_Supplier_Application.ProductService.InsertProductRequest request) {
            return base.Channel.InsertProduct(request);
        }
        
        public int InsertProduct(string title, string description, string filePath, int supplierId) {
            TechFix_Supplier_Application.ProductService.InsertProductRequest inValue = new TechFix_Supplier_Application.ProductService.InsertProductRequest();
            inValue.Body = new TechFix_Supplier_Application.ProductService.InsertProductRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.filePath = filePath;
            inValue.Body.supplierId = supplierId;
            TechFix_Supplier_Application.ProductService.InsertProductResponse retVal = ((TechFix_Supplier_Application.ProductService.ProductServiceSoap)(this)).InsertProduct(inValue);
            return retVal.Body.InsertProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.InsertProductResponse> TechFix_Supplier_Application.ProductService.ProductServiceSoap.InsertProductAsync(TechFix_Supplier_Application.ProductService.InsertProductRequest request) {
            return base.Channel.InsertProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.InsertProductResponse> InsertProductAsync(string title, string description, string filePath, int supplierId) {
            TechFix_Supplier_Application.ProductService.InsertProductRequest inValue = new TechFix_Supplier_Application.ProductService.InsertProductRequest();
            inValue.Body = new TechFix_Supplier_Application.ProductService.InsertProductRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.filePath = filePath;
            inValue.Body.supplierId = supplierId;
            return ((TechFix_Supplier_Application.ProductService.ProductServiceSoap)(this)).InsertProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Supplier_Application.ProductService.GetAllListedProductsResponse TechFix_Supplier_Application.ProductService.ProductServiceSoap.GetAllListedProducts(TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest request) {
            return base.Channel.GetAllListedProducts(request);
        }
        
        public TechFix_Supplier_Application.ProductService.ProductCard[] GetAllListedProducts() {
            TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest inValue = new TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest();
            inValue.Body = new TechFix_Supplier_Application.ProductService.GetAllListedProductsRequestBody();
            TechFix_Supplier_Application.ProductService.GetAllListedProductsResponse retVal = ((TechFix_Supplier_Application.ProductService.ProductServiceSoap)(this)).GetAllListedProducts(inValue);
            return retVal.Body.GetAllListedProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.GetAllListedProductsResponse> TechFix_Supplier_Application.ProductService.ProductServiceSoap.GetAllListedProductsAsync(TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest request) {
            return base.Channel.GetAllListedProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Supplier_Application.ProductService.GetAllListedProductsResponse> GetAllListedProductsAsync() {
            TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest inValue = new TechFix_Supplier_Application.ProductService.GetAllListedProductsRequest();
            inValue.Body = new TechFix_Supplier_Application.ProductService.GetAllListedProductsRequestBody();
            return ((TechFix_Supplier_Application.ProductService.ProductServiceSoap)(this)).GetAllListedProductsAsync(inValue);
        }
    }
}
