//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix_Client_Application.AuthenticationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsAuthenticatedField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsAuthenticated {
            get {
                return this.IsAuthenticatedField;
            }
            set {
                if ((this.IsAuthenticatedField.Equals(value) != true)) {
                    this.IsAuthenticatedField = value;
                    this.RaisePropertyChanged("IsAuthenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedAtField, value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.AuthenticationSoap")]
    public interface AuthenticationSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        TechFix_Client_Application.AuthenticationService.AuthenticateUserResponse AuthenticateUser(TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.AuthenticateUserResponse> AuthenticateUserAsync(TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateSupplier", ReplyAction="*")]
        TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponse AuthenticateSupplier(TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponse> AuthenticateSupplierAsync(TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmailExists", ReplyAction="*")]
        TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponse CheckEmailExists(TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmailExists", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponse> CheckEmailExistsAsync(TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest request);
        
        // CODEGEN: Generating message contract since element name password from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPasswordExists", ReplyAction="*")]
        TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponse CheckPasswordExists(TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPasswordExists", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponse> CheckPasswordExistsAsync(TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmailFormat", ReplyAction="*")]
        TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponse CheckEmailFormat(TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmailFormat", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponse> CheckEmailFormatAsync(TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest request);
        
        // CODEGEN: Generating message contract since element name password from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPasswordFormat", ReplyAction="*")]
        TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponse CheckPasswordFormat(TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPasswordFormat", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponse> CheckPasswordFormatAsync(TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(TechFix_Client_Application.AuthenticationService.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(TechFix_Client_Application.AuthenticationService.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFix_Client_Application.AuthenticationService.AuthenticationResponse AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(TechFix_Client_Application.AuthenticationService.AuthenticationResponse AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateSupplier", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequestBody Body;
        
        public AuthenticateSupplierRequest() {
        }
        
        public AuthenticateSupplierRequest(TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateSupplierRequestBody() {
        }
        
        public AuthenticateSupplierRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponseBody Body;
        
        public AuthenticateSupplierResponse() {
        }
        
        public AuthenticateSupplierResponse(TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFix_Client_Application.AuthenticationService.AuthenticationResponse AuthenticateSupplierResult;
        
        public AuthenticateSupplierResponseBody() {
        }
        
        public AuthenticateSupplierResponseBody(TechFix_Client_Application.AuthenticationService.AuthenticationResponse AuthenticateSupplierResult) {
            this.AuthenticateSupplierResult = AuthenticateSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEmailExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEmailExists", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequestBody Body;
        
        public CheckEmailExistsRequest() {
        }
        
        public CheckEmailExistsRequest(TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEmailExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public CheckEmailExistsRequestBody() {
        }
        
        public CheckEmailExistsRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEmailExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEmailExistsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponseBody Body;
        
        public CheckEmailExistsResponse() {
        }
        
        public CheckEmailExistsResponse(TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEmailExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckEmailExistsResult;
        
        public CheckEmailExistsResponseBody() {
        }
        
        public CheckEmailExistsResponseBody(bool CheckEmailExistsResult) {
            this.CheckEmailExistsResult = CheckEmailExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPasswordExists", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequestBody Body;
        
        public CheckPasswordExistsRequest() {
        }
        
        public CheckPasswordExistsRequest(TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPasswordExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        public CheckPasswordExistsRequestBody() {
        }
        
        public CheckPasswordExistsRequestBody(string password) {
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPasswordExistsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponseBody Body;
        
        public CheckPasswordExistsResponse() {
        }
        
        public CheckPasswordExistsResponse(TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPasswordExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckPasswordExistsResult;
        
        public CheckPasswordExistsResponseBody() {
        }
        
        public CheckPasswordExistsResponseBody(bool CheckPasswordExistsResult) {
            this.CheckPasswordExistsResult = CheckPasswordExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEmailFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEmailFormat", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequestBody Body;
        
        public CheckEmailFormatRequest() {
        }
        
        public CheckEmailFormatRequest(TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEmailFormatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public CheckEmailFormatRequestBody() {
        }
        
        public CheckEmailFormatRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEmailFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEmailFormatResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponseBody Body;
        
        public CheckEmailFormatResponse() {
        }
        
        public CheckEmailFormatResponse(TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEmailFormatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckEmailFormatResult;
        
        public CheckEmailFormatResponseBody() {
        }
        
        public CheckEmailFormatResponseBody(bool CheckEmailFormatResult) {
            this.CheckEmailFormatResult = CheckEmailFormatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPasswordFormat", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequestBody Body;
        
        public CheckPasswordFormatRequest() {
        }
        
        public CheckPasswordFormatRequest(TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPasswordFormatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        public CheckPasswordFormatRequestBody() {
        }
        
        public CheckPasswordFormatRequestBody(string password) {
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPasswordFormatResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponseBody Body;
        
        public CheckPasswordFormatResponse() {
        }
        
        public CheckPasswordFormatResponse(TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPasswordFormatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckPasswordFormatResult;
        
        public CheckPasswordFormatResponseBody() {
        }
        
        public CheckPasswordFormatResponseBody(bool CheckPasswordFormatResult) {
            this.CheckPasswordFormatResult = CheckPasswordFormatResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationSoapChannel : TechFix_Client_Application.AuthenticationService.AuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationSoapClient : System.ServiceModel.ClientBase<TechFix_Client_Application.AuthenticationService.AuthenticationSoap>, TechFix_Client_Application.AuthenticationService.AuthenticationSoap {
        
        public AuthenticationSoapClient() {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.AuthenticationService.AuthenticateUserResponse TechFix_Client_Application.AuthenticationService.AuthenticationSoap.AuthenticateUser(TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public TechFix_Client_Application.AuthenticationService.AuthenticationResponse AuthenticateUser(string username, string password) {
            TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest inValue = new TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.AuthenticateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            TechFix_Client_Application.AuthenticationService.AuthenticateUserResponse retVal = ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.AuthenticateUserResponse> TechFix_Client_Application.AuthenticationService.AuthenticationSoap.AuthenticateUserAsync(TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.AuthenticateUserResponse> AuthenticateUserAsync(string username, string password) {
            TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest inValue = new TechFix_Client_Application.AuthenticationService.AuthenticateUserRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.AuthenticateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponse TechFix_Client_Application.AuthenticationService.AuthenticationSoap.AuthenticateSupplier(TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest request) {
            return base.Channel.AuthenticateSupplier(request);
        }
        
        public TechFix_Client_Application.AuthenticationService.AuthenticationResponse AuthenticateSupplier(string username, string password) {
            TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest inValue = new TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponse retVal = ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).AuthenticateSupplier(inValue);
            return retVal.Body.AuthenticateSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponse> TechFix_Client_Application.AuthenticationService.AuthenticationSoap.AuthenticateSupplierAsync(TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest request) {
            return base.Channel.AuthenticateSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.AuthenticateSupplierResponse> AuthenticateSupplierAsync(string username, string password) {
            TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest inValue = new TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.AuthenticateSupplierRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).AuthenticateSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponse TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckEmailExists(TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest request) {
            return base.Channel.CheckEmailExists(request);
        }
        
        public bool CheckEmailExists(string email) {
            TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequestBody();
            inValue.Body.email = email;
            TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponse retVal = ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckEmailExists(inValue);
            return retVal.Body.CheckEmailExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponse> TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckEmailExistsAsync(TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest request) {
            return base.Channel.CheckEmailExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckEmailExistsResponse> CheckEmailExistsAsync(string email) {
            TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckEmailExistsRequestBody();
            inValue.Body.email = email;
            return ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckEmailExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponse TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckPasswordExists(TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest request) {
            return base.Channel.CheckPasswordExists(request);
        }
        
        public bool CheckPasswordExists(string password) {
            TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequestBody();
            inValue.Body.password = password;
            TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponse retVal = ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckPasswordExists(inValue);
            return retVal.Body.CheckPasswordExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponse> TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckPasswordExistsAsync(TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest request) {
            return base.Channel.CheckPasswordExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckPasswordExistsResponse> CheckPasswordExistsAsync(string password) {
            TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckPasswordExistsRequestBody();
            inValue.Body.password = password;
            return ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckPasswordExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponse TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckEmailFormat(TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest request) {
            return base.Channel.CheckEmailFormat(request);
        }
        
        public bool CheckEmailFormat(string email) {
            TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequestBody();
            inValue.Body.email = email;
            TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponse retVal = ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckEmailFormat(inValue);
            return retVal.Body.CheckEmailFormatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponse> TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckEmailFormatAsync(TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest request) {
            return base.Channel.CheckEmailFormatAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckEmailFormatResponse> CheckEmailFormatAsync(string email) {
            TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckEmailFormatRequestBody();
            inValue.Body.email = email;
            return ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckEmailFormatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponse TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckPasswordFormat(TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest request) {
            return base.Channel.CheckPasswordFormat(request);
        }
        
        public bool CheckPasswordFormat(string password) {
            TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequestBody();
            inValue.Body.password = password;
            TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponse retVal = ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckPasswordFormat(inValue);
            return retVal.Body.CheckPasswordFormatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponse> TechFix_Client_Application.AuthenticationService.AuthenticationSoap.CheckPasswordFormatAsync(TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest request) {
            return base.Channel.CheckPasswordFormatAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.AuthenticationService.CheckPasswordFormatResponse> CheckPasswordFormatAsync(string password) {
            TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest inValue = new TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequest();
            inValue.Body = new TechFix_Client_Application.AuthenticationService.CheckPasswordFormatRequestBody();
            inValue.Body.password = password;
            return ((TechFix_Client_Application.AuthenticationService.AuthenticationSoap)(this)).CheckPasswordFormatAsync(inValue);
        }
    }
}
