//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix_Supplier_Application.QuotationServiceMod {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Quotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuotationIDField;
        
        private int SupplierIDField;
        
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuotationID {
            get {
                return this.QuotationIDField;
            }
            set {
                if ((this.QuotationIDField.Equals(value) != true)) {
                    this.QuotationIDField = value;
                    this.RaisePropertyChanged("QuotationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Attachment {
            get {
                return this.AttachmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentField, value) != true)) {
                    this.AttachmentField = value;
                    this.RaisePropertyChanged("Attachment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SupplierResponse {
            get {
                return this.SupplierResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierResponseField, value) != true)) {
                    this.SupplierResponseField = value;
                    this.RaisePropertyChanged("SupplierResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuotationServiceMod.QuotationServiceSoap")]
    public interface QuotationServiceSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertQuotation", ReplyAction="*")]
        TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponse InsertQuotation(TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertQuotation", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponse> InsertQuotationAsync(TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllQuotationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuotations", ReplyAction="*")]
        TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponse GetAllQuotations(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuotations", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponse> GetAllQuotationsAsync(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllQuotationsBySupplierResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuotationsBySupplier", ReplyAction="*")]
        TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponse GetAllQuotationsBySupplier(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuotationsBySupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponse> GetAllQuotationsBySupplierAsync(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertQuotationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertQuotation", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequestBody Body;
        
        public InsertQuotationRequest() {
        }
        
        public InsertQuotationRequest(TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertQuotationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int supplierId;
        
        public InsertQuotationRequestBody() {
        }
        
        public InsertQuotationRequestBody(string title, string description, string filePath, int supplierId) {
            this.title = title;
            this.description = description;
            this.filePath = filePath;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertQuotationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertQuotationResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponseBody Body;
        
        public InsertQuotationResponse() {
        }
        
        public InsertQuotationResponse(TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertQuotationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertQuotationResult;
        
        public InsertQuotationResponseBody() {
        }
        
        public InsertQuotationResponseBody(int InsertQuotationResult) {
            this.InsertQuotationResult = InsertQuotationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuotationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuotations", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequestBody Body;
        
        public GetAllQuotationsRequest() {
        }
        
        public GetAllQuotationsRequest(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllQuotationsRequestBody {
        
        public GetAllQuotationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuotationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuotationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponseBody Body;
        
        public GetAllQuotationsResponse() {
        }
        
        public GetAllQuotationsResponse(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllQuotationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotationsResult;
        
        public GetAllQuotationsResponseBody() {
        }
        
        public GetAllQuotationsResponseBody(TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotationsResult) {
            this.GetAllQuotationsResult = GetAllQuotationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuotationsBySupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuotationsBySupplier", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequestBody Body;
        
        public GetAllQuotationsBySupplierRequest() {
        }
        
        public GetAllQuotationsBySupplierRequest(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllQuotationsBySupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierID;
        
        public GetAllQuotationsBySupplierRequestBody() {
        }
        
        public GetAllQuotationsBySupplierRequestBody(int supplierID) {
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuotationsBySupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuotationsBySupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponseBody Body;
        
        public GetAllQuotationsBySupplierResponse() {
        }
        
        public GetAllQuotationsBySupplierResponse(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllQuotationsBySupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotationsBySupplierResult;
        
        public GetAllQuotationsBySupplierResponseBody() {
        }
        
        public GetAllQuotationsBySupplierResponseBody(TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotationsBySupplierResult) {
            this.GetAllQuotationsBySupplierResult = GetAllQuotationsBySupplierResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuotationServiceSoapChannel : TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuotationServiceSoapClient : System.ServiceModel.ClientBase<TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap>, TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap {
        
        public QuotationServiceSoapClient() {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponse TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap.InsertQuotation(TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest request) {
            return base.Channel.InsertQuotation(request);
        }
        
        public int InsertQuotation(string title, string description, string filePath, int supplierId) {
            TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest inValue = new TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest();
            inValue.Body = new TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.filePath = filePath;
            inValue.Body.supplierId = supplierId;
            TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponse retVal = ((TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap)(this)).InsertQuotation(inValue);
            return retVal.Body.InsertQuotationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponse> TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap.InsertQuotationAsync(TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest request) {
            return base.Channel.InsertQuotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationResponse> InsertQuotationAsync(string title, string description, string filePath, int supplierId) {
            TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest inValue = new TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequest();
            inValue.Body = new TechFix_Supplier_Application.QuotationServiceMod.InsertQuotationRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.filePath = filePath;
            inValue.Body.supplierId = supplierId;
            return ((TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap)(this)).InsertQuotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponse TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap.GetAllQuotations(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest request) {
            return base.Channel.GetAllQuotations(request);
        }
        
        public TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotations() {
            TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest inValue = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest();
            inValue.Body = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequestBody();
            TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponse retVal = ((TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap)(this)).GetAllQuotations(inValue);
            return retVal.Body.GetAllQuotationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponse> TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap.GetAllQuotationsAsync(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest request) {
            return base.Channel.GetAllQuotationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsResponse> GetAllQuotationsAsync() {
            TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest inValue = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequest();
            inValue.Body = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsRequestBody();
            return ((TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap)(this)).GetAllQuotationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponse TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap.GetAllQuotationsBySupplier(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest request) {
            return base.Channel.GetAllQuotationsBySupplier(request);
        }
        
        public TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotationsBySupplier(int supplierID) {
            TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest inValue = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest();
            inValue.Body = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequestBody();
            inValue.Body.supplierID = supplierID;
            TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponse retVal = ((TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap)(this)).GetAllQuotationsBySupplier(inValue);
            return retVal.Body.GetAllQuotationsBySupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponse> TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap.GetAllQuotationsBySupplierAsync(TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest request) {
            return base.Channel.GetAllQuotationsBySupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierResponse> GetAllQuotationsBySupplierAsync(int supplierID) {
            TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest inValue = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequest();
            inValue.Body = new TechFix_Supplier_Application.QuotationServiceMod.GetAllQuotationsBySupplierRequestBody();
            inValue.Body.supplierID = supplierID;
            return ((TechFix_Supplier_Application.QuotationServiceMod.QuotationServiceSoap)(this)).GetAllQuotationsBySupplierAsync(inValue);
        }
    }
}
