//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix_Client_Application.QuotationServiceMod {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuotationServiceMod.QuotationServiceSoap")]
    public interface QuotationServiceSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertQuotation", ReplyAction="*")]
        TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponse InsertQuotation(TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertQuotation", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponse> InsertQuotationAsync(TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllQuotationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuotations", ReplyAction="*")]
        TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponse GetAllQuotations(TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuotations", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponse> GetAllQuotationsAsync(TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertQuotationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertQuotation", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequestBody Body;
        
        public InsertQuotationRequest() {
        }
        
        public InsertQuotationRequest(TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertQuotationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int supplierId;
        
        public InsertQuotationRequestBody() {
        }
        
        public InsertQuotationRequestBody(string title, string description, string filePath, int supplierId) {
            this.title = title;
            this.description = description;
            this.filePath = filePath;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertQuotationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertQuotationResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponseBody Body;
        
        public InsertQuotationResponse() {
        }
        
        public InsertQuotationResponse(TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertQuotationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertQuotationResult;
        
        public InsertQuotationResponseBody() {
        }
        
        public InsertQuotationResponseBody(int InsertQuotationResult) {
            this.InsertQuotationResult = InsertQuotationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuotationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuotations", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequestBody Body;
        
        public GetAllQuotationsRequest() {
        }
        
        public GetAllQuotationsRequest(TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllQuotationsRequestBody {
        
        public GetAllQuotationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuotationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuotationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponseBody Body;
        
        public GetAllQuotationsResponse() {
        }
        
        public GetAllQuotationsResponse(TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllQuotationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotationsResult;
        
        public GetAllQuotationsResponseBody() {
        }
        
        public GetAllQuotationsResponseBody(TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotationsResult) {
            this.GetAllQuotationsResult = GetAllQuotationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuotationServiceSoapChannel : TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuotationServiceSoapClient : System.ServiceModel.ClientBase<TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap>, TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap {
        
        public QuotationServiceSoapClient() {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponse TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap.InsertQuotation(TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest request) {
            return base.Channel.InsertQuotation(request);
        }
        
        public int InsertQuotation(string title, string description, string filePath, int supplierId) {
            TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest inValue = new TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest();
            inValue.Body = new TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.filePath = filePath;
            inValue.Body.supplierId = supplierId;
            TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponse retVal = ((TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap)(this)).InsertQuotation(inValue);
            return retVal.Body.InsertQuotationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponse> TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap.InsertQuotationAsync(TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest request) {
            return base.Channel.InsertQuotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.QuotationServiceMod.InsertQuotationResponse> InsertQuotationAsync(string title, string description, string filePath, int supplierId) {
            TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest inValue = new TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequest();
            inValue.Body = new TechFix_Client_Application.QuotationServiceMod.InsertQuotationRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.filePath = filePath;
            inValue.Body.supplierId = supplierId;
            return ((TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap)(this)).InsertQuotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponse TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap.GetAllQuotations(TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest request) {
            return base.Channel.GetAllQuotations(request);
        }
        
        public TechFix_Supplier_Application.QuotationServiceMod.Quotation[] GetAllQuotations() {
            TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest inValue = new TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest();
            inValue.Body = new TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequestBody();
            TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponse retVal = ((TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap)(this)).GetAllQuotations(inValue);
            return retVal.Body.GetAllQuotationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponse> TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap.GetAllQuotationsAsync(TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest request) {
            return base.Channel.GetAllQuotationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsResponse> GetAllQuotationsAsync() {
            TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest inValue = new TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequest();
            inValue.Body = new TechFix_Client_Application.QuotationServiceMod.GetAllQuotationsRequestBody();
            return ((TechFix_Client_Application.QuotationServiceMod.QuotationServiceSoap)(this)).GetAllQuotationsAsync(inValue);
        }
    }
}
